-- Copy the MySQL `events` table into PostgreSQL.
--
-- 1) Export from MySQL to CSV with this column order:
--
--    id,title,description,event_type,event_date,event_time,location,created_by,created_at,updated_at
--
--    Example MySQL query:
--
--    SELECT
--      id,
--      title,
--      description,
--      event_type,
--      event_date,
--      event_time,
--      location,
--      created_by,
--      created_at,
--      updated_at
--    FROM events
--    ORDER BY id;
--
-- 2) Save the file as:
--
--    migrations/data/events.csv
--
-- 3) Run from this project folder with psql:
--
--    psql "$DATABASE_URL" -f migrations/copy_events_mysql_to_postgres.sql

BEGIN;

CREATE TABLE IF NOT EXISTS events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  event_type VARCHAR(20) NOT NULL DEFAULT 'other',
  event_date DATE NOT NULL,
  event_time TIME NOT NULL,
  location VARCHAR(255),
  created_by INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT events_event_type_check
    CHECK (event_type IN ('prayer', 'lecture', 'class', 'service', 'other')),
  CONSTRAINT fk_events_user
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_events_date ON events(event_date);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);

-- Uncomment this if you want to replace all Postgres events with the MySQL export.
-- TRUNCATE TABLE events RESTART IDENTITY;

CREATE TEMP TABLE events_import (
  id INTEGER,
  title VARCHAR(255),
  description TEXT,
  event_type VARCHAR(20),
  event_date DATE,
  event_time TIME,
  location VARCHAR(255),
  created_by INTEGER,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

\copy events_import (
  id,
  title,
  description,
  event_type,
  event_date,
  event_time,
  location,
  created_by,
  created_at,
  updated_at
)
FROM 'migrations/data/events.csv'
WITH (
  FORMAT csv,
  HEADER true,
  NULL '',
  ENCODING 'UTF8'
);

INSERT INTO events (
  id,
  title,
  description,
  event_type,
  event_date,
  event_time,
  location,
  created_by,
  created_at,
  updated_at
)
SELECT
  events_import.id,
  events_import.title,
  events_import.description,
  COALESCE(NULLIF(events_import.event_type, ''), 'other'),
  events_import.event_date,
  events_import.event_time,
  events_import.location,
  CASE
    WHEN events_import.created_by IS NOT NULL
     AND EXISTS (SELECT 1 FROM users WHERE users.id = events_import.created_by)
    THEN events_import.created_by
    ELSE NULL
  END,
  COALESCE(events_import.created_at, CURRENT_TIMESTAMP),
  COALESCE(events_import.updated_at, CURRENT_TIMESTAMP)
FROM events_import
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  event_type = EXCLUDED.event_type,
  event_date = EXCLUDED.event_date,
  event_time = EXCLUDED.event_time,
  location = EXCLUDED.location,
  created_by = EXCLUDED.created_by,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

SELECT setval(
  pg_get_serial_sequence('events', 'id'),
  COALESCE((SELECT MAX(id) FROM events), 1),
  true
);

COMMIT;
