import fs from "node:fs/promises";
import path from "node:path";
import dotenv from "dotenv";
import mysql from "mysql2/promise";

dotenv.config({ path: ".env.local" });

const outputPath = path.join("migrations", "insert_recurring_events_postgres.sql");
const insertOnlyOutputPath = path.join(
  "migrations",
  "insert_recurring_events_postgres_only.sql"
);

const dbConfig = {
  host: process.env.DB_HOST,
  port: process.env.DB_PORT || 3306,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
};

const columns = [
  "id",
  "title",
  "description",
  "event_type",
  "event_time",
  "location",
  "is_active",
  "days_of_week",
  "created_by",
  "created_at",
  "updated_at",
];

function formatDate(value) {
  const pad = (number) => String(number).padStart(2, "0");
  return [
    value.getFullYear(),
    pad(value.getMonth() + 1),
    pad(value.getDate()),
  ].join("-");
}

function formatDateTime(value) {
  const pad = (number) => String(number).padStart(2, "0");
  return `${formatDate(value)} ${pad(value.getHours())}:${pad(value.getMinutes())}:${pad(value.getSeconds())}`;
}

function sqlString(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function normalizeJson(value) {
  if (value === null || value === undefined || value === "") {
    return "[]";
  }

  if (typeof value === "object" && !(value instanceof Date)) {
    return JSON.stringify(value);
  }

  try {
    return JSON.stringify(JSON.parse(String(value)));
  } catch {
    return "[]";
  }
}

function sqlValue(value, column) {
  if (value === null || value === undefined) {
    return "NULL";
  }

  if (column === "is_active") {
    return value === true || value === 1 || value === "1" ? "TRUE" : "FALSE";
  }

  if (column === "days_of_week") {
    return `${sqlString(normalizeJson(value))}::jsonb`;
  }

  if (value instanceof Date) {
    return sqlString(formatDateTime(value));
  }

  if (typeof value === "number") {
    return String(value);
  }

  return sqlString(value);
}

function rowToValues(row) {
  return `(${columns.map((column) => sqlValue(row[column], column)).join(", ")})`;
}

const connection = await mysql.createConnection(dbConfig);

try {
  const [rows] = await connection.query(
    `SELECT ${columns.map((column) => `\`${column}\``).join(", ")}
     FROM recurring_events
     ORDER BY id`
  );

  const header = `-- Generated from MySQL recurring_events table for PostgreSQL.
-- Rows: ${rows.length}

BEGIN;

CREATE TABLE IF NOT EXISTS recurring_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  event_type VARCHAR(20) NOT NULL DEFAULT 'other',
  event_time TIME NOT NULL,
  location VARCHAR(255),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  days_of_week JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT recurring_events_event_type_check
    CHECK (event_type IN ('prayer', 'lecture', 'class', 'service', 'other'))
);

CREATE INDEX IF NOT EXISTS idx_recurring_active ON recurring_events(is_active);

`;

  let sql = header;
  let insertOnlySql = `-- Paste this into the PostgreSQL SQL editor.
-- Generated from MySQL recurring_events table.
-- Rows: ${rows.length}

`;

  if (rows.length > 0) {
    const insertStatement = `INSERT INTO recurring_events (${columns.join(", ")}) VALUES\n${rows
      .map(rowToValues)
      .join(",\n")}
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  event_type = EXCLUDED.event_type,
  event_time = EXCLUDED.event_time,
  location = EXCLUDED.location,
  is_active = EXCLUDED.is_active,
  days_of_week = EXCLUDED.days_of_week,
  created_by = EXCLUDED.created_by,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;`;

    sql += `${insertStatement}\n\n`;
    insertOnlySql += `${insertStatement}\n\n`;
  }

  const sequenceSql = `SELECT setval(
  pg_get_serial_sequence('recurring_events', 'id'),
  COALESCE((SELECT MAX(id) FROM recurring_events), 1),
  true
);`;

  sql += `${sequenceSql}

COMMIT;
`;

  insertOnlySql += `${sequenceSql}
`;

  await fs.writeFile(outputPath, sql, "utf8");
  await fs.writeFile(insertOnlyOutputPath, insertOnlySql, "utf8");
  console.log(`Wrote ${rows.length} recurring events to ${outputPath}`);
  console.log(`Wrote insert-only SQL to ${insertOnlyOutputPath}`);
} finally {
  await connection.end();
}
