import fs from "node:fs/promises";
import path from "node:path";
import dotenv from "dotenv";
import mysql from "mysql2/promise";

dotenv.config({ path: ".env.local" });

const outputPath = path.join("migrations", "insert_events_postgres.sql");

const dbConfig = {
  host: process.env.DB_HOST,
  port: process.env.DB_PORT || 3306,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
};

const columns = [
  "id",
  "title",
  "description",
  "event_type",
  "event_date",
  "event_time",
  "location",
  "created_by",
  "created_at",
  "updated_at",
];

function formatDate(value) {
  const pad = (number) => String(number).padStart(2, "0");
  return [
    value.getFullYear(),
    pad(value.getMonth() + 1),
    pad(value.getDate()),
  ].join("-");
}

function formatDateTime(value) {
  const pad = (number) => String(number).padStart(2, "0");
  return `${formatDate(value)} ${pad(value.getHours())}:${pad(value.getMinutes())}:${pad(value.getSeconds())}`;
}

function sqlString(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlValue(value, column) {
  if (value === null || value === undefined) {
    return "NULL";
  }

  if (value instanceof Date) {
    if (column === "event_date") {
      return sqlString(formatDate(value));
    }

    return sqlString(formatDateTime(value));
  }

  if (typeof value === "number") {
    return String(value);
  }

  return sqlString(value);
}

function rowToValues(row) {
  return `(${columns.map((column) => sqlValue(row[column], column)).join(", ")})`;
}

const connection = await mysql.createConnection(dbConfig);

try {
  const [rows] = await connection.query(
    `SELECT ${columns.map((column) => `\`${column}\``).join(", ")}
     FROM events
     ORDER BY id`
  );

  const header = `-- Generated from MySQL events table for PostgreSQL.
-- Rows: ${rows.length}

BEGIN;

CREATE TABLE IF NOT EXISTS events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  event_type VARCHAR(20) NOT NULL DEFAULT 'other',
  event_date DATE NOT NULL,
  event_time TIME NOT NULL,
  location VARCHAR(255),
  created_by INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT events_event_type_check
    CHECK (event_type IN ('prayer', 'lecture', 'class', 'service', 'other'))
);

`;

  let sql = header;

  if (rows.length > 0) {
    sql += `INSERT INTO events (${columns.join(", ")}) VALUES\n`;
    sql += rows.map(rowToValues).join(",\n");
    sql += `\nON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  event_type = EXCLUDED.event_type,
  event_date = EXCLUDED.event_date,
  event_time = EXCLUDED.event_time,
  location = EXCLUDED.location,
  created_by = EXCLUDED.created_by,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

`;
  }

  sql += `SELECT setval(
  pg_get_serial_sequence('events', 'id'),
  COALESCE((SELECT MAX(id) FROM events), 1),
  true
);

COMMIT;
`;

  await fs.writeFile(outputPath, sql, "utf8");
  console.log(`Wrote ${rows.length} events to ${outputPath}`);
} finally {
  await connection.end();
}
