-- Generated from MySQL events table for PostgreSQL.
-- Rows: 0

BEGIN;

CREATE TABLE IF NOT EXISTS events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  event_type VARCHAR(20) NOT NULL DEFAULT 'other',
  event_date DATE NOT NULL,
  event_time TIME NOT NULL,
  location VARCHAR(255),
  created_by INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT events_event_type_check
    CHECK (event_type IN ('prayer', 'lecture', 'class', 'service', 'other'))
);

SELECT setval(
  pg_get_serial_sequence('events', 'id'),
  COALESCE((SELECT MAX(id) FROM events), 1),
  true
);

COMMIT;
