-- Generated from MySQL recurring_events table for PostgreSQL.
-- Rows: 2

BEGIN;

CREATE TABLE IF NOT EXISTS recurring_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  event_type VARCHAR(20) NOT NULL DEFAULT 'other',
  event_time TIME NOT NULL,
  location VARCHAR(255),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  days_of_week JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT recurring_events_event_type_check
    CHECK (event_type IN ('prayer', 'lecture', 'class', 'service', 'other'))
);

CREATE INDEX IF NOT EXISTS idx_recurring_active ON recurring_events(is_active);

INSERT INTO recurring_events (id, title, description, event_type, event_time, location, is_active, days_of_week, created_by, created_at, updated_at) VALUES
(1, 'שיעור עם הרב מנחם מיידנצ''יק', '', 'class', '09:10:00', '', TRUE, '[1,2,0]'::jsonb, 1, '2026-04-05 07:01:23', '2026-04-05 08:17:20'),
(2, 'תניא עם הרב פז', '', 'class', '10:30:00', '', TRUE, '[0]'::jsonb, 1, '2026-04-05 07:18:14', '2026-04-05 08:28:14')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  event_type = EXCLUDED.event_type,
  event_time = EXCLUDED.event_time,
  location = EXCLUDED.location,
  is_active = EXCLUDED.is_active,
  days_of_week = EXCLUDED.days_of_week,
  created_by = EXCLUDED.created_by,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

SELECT setval(
  pg_get_serial_sequence('recurring_events', 'id'),
  COALESCE((SELECT MAX(id) FROM recurring_events), 1),
  true
);

COMMIT;
